import java.util.Scanner;

public interface Player
{
	// Connect with a Board reference
	void setBoardReference(Board b);
	
	// Work out what move to do
	void generateMove(Scanner scan);
	
	// Return the move generated by generateMove()
	public Move getMove();
	
	// Only allow the setting of the token ONCE
	public void setBoardToken(BoardToken token);
	
	// Return the player's BoardToken
	public BoardToken getBoardToken();

}
